### ISSUE TITLE
About API Links & Inscodes

### ISSUE THREAD

**Issue by mnwato** [SinaMobasheri/TehranSE#3]
http://tsetmc.com/tsev2/data/instinfodata.aspx
http://www.tsetmc.com/tsev2/data/instinfofast.aspx

What is the difference between these links?(instinfodata and instinfofast)
Today I downloaded content of the second link every 5sec but every time I received the same one
Which one is faster?

The other question is :
I entered different "csecval" for a specific inscode I just received the summarized and not summarized data, so the question is why they use csecval in url structure when the correctio of that is not important?

I tried these ones:
http://tsetmc.com/tsev2/data/instinfodata.aspx?i=5987841496184505&c=44
http://tsetmc.com/tsev2/data/instinfodata.aspx?i=5987841496184505&c=11

Thanks in advaced

**Comment by SinaMobasheri** [comment]
*what is the difference between these links?* **have no idea**
i think these are different in backend processing but in frontend they are the same \
and about *every time i received the same one* if you are sure everything was right and it was in business hours i have one guess, i had seen something like that when i send too many request in short amount of time 

*other question* **this is not the only one !**
yse i also noticed too, even if you pass any string to c parameter it has not effects on result, look at the price history hidden api in that api there is url parameter called *A* and it has no effect at all !

**but i decided when the JavaScript's AJAX send these call like this i send it too it's better to stick to it**

**Comment by mnwato** [comment]
This is a simple code to save data in a txt file, but the result always is the same: ( I ran during the opening market)

################################################
import requests
import schedule
import time
import datetime

khodro= requests.get('http://www.tsetmc.com/tsev2/data/instinfofast.aspx?i=65883838195688438&c=34')

def job():
	currentDT = datetime.datetime.now()
	year = currentDT.year
	month = currentDT.month
	day = currentDT.day
	hour = currentDT.hour
	minute = currentDT.minute
	second = currentDT.second

	file_khodro=open(f"C:/Users/mostafa/Desktop/reports/khodro/khodro {year}-{month}-{day} {hour}-{minute}-{second}.txt","a")
	file_khodro.write(khodro.text)
	file_khodro.close()

	print(f"txt file has been saved at {hour}:{minute}:{second}","\n")

def job2():
	schedule.every(59).seconds.do(job)

schedule.every(1).day.at("11:09").do(job2)

while True:
    schedule.run_pending()
    time.sleep(1)
##################################################

This is funny that in the browser it will renew after every refresh.

**Comment by SinaMobasheri** [comment]
i can't findout what wrong about this but i write my code and i get *qd1* and print it and everytime its different, looks like its fine !
```python
from requests import get
from time import sleep

def check(inscode, csecval):

    url = "http://www.tsetmc.com/tsev2/data/instinfofast.aspx"
    payload = {"i": inscode, "c": csecval}

    sponse = get(url, params=payload)
    sponse = sponse.text.split(";")[2].split("@")[1]
    print(sponse)


if __name__ == "__main__":
    
    while True:
        
        check("65883838195688438", "34")
        sleep(5)
```
some output that i got in 11:55
```python
1015503886
1015715054
1015729089
1015716890
1016232030
1016211301
1016163817
```

**Comment by mnwato** [comment]
Thanks
I correct that. I forgot to used get.request in the function

But it sometimes gives me a long data and sometimes short ones!

By the way is there a way to get groups of inscodeinfo or total inscodeinfo using your code? (You know it takes lots of time if we want to collect for example 700 inscodes, out of that in a real time situation.

**Comment by SinaMobasheri** [comment]
*But it sometimes gives me a long data and sometimes short ones!* 
yes, i can't figure out why it act like that but some of data always available and i clean and return them with `getinst()` method

### about access to groups of inscodes
*is there a way to get groups of inscodeinfo?*
yes there is ! see [my virgool post](https://virgool.io/@sinamobasheri) for more information about `report()` and `update()` function that's helps you to access to groups of shares and filter it with market or industrial groups, I hope this is what you are looking for
